config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  root 'users#index'

  resources :users, only: [:index, :show] do 
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:index, :new, :create] 
      resources :likes, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User'

  after_create :update_posts_counter

  def update_posts_counter
    post.increment!(:comments_counter)
  end

  private :update_posts_counter
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :update_posts_counter

  def update_posts_counter
    post.increment!(:likes_counter)
  end

  private :update_posts_counter
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_create :update_users_counter

  def recent_five
    comments.order(created_at: :desc).limit(5)
  end

  def update_users_counter
    author.increment!(:posts_counter)
  end

  private :update_users_counter
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :author_id, dependent: :destroy
  has_many :likes, foreign_key: :author_id, dependent: :destroy

  def first_three
    posts.order(created_at: :asc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments
  end

  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
  end

  def create
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = params[:post_id]

    if @comment.save
      redirect_to user_post_comments_path(current_user, @comment.post_id)
    else
      render :create
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.new
    @like.post_id = params[:post_id]
    if @like.save
      flash[:success] = 'You liked this post'
      redirect_to user_post_path(current_user, @like.post)
    else
      flash.now[:error] = 'like failed'
      render :create
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments).page(params[:page]).per(5)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:success] = 'Post created successfully'
      redirect_to user_posts_path(current_user, @post)
    else
      flash.now[:error] = 'Error creating post'
      render :new
    end
  end

  def show
    set_post
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  def index
    @users = User.all
  end

  def show
    set_user
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/users_helpers.rb
module UsersHelper
end

app/views/comments/index.html.erb
<%= render 'layouts/header' %>
<section class="indent">
    <h3>Comments</h3>
    <br>
    <button class="cancel-btn link">
        <%= link_to 'Back to post', user_post_path(@post.author, @post), style: 'color: black; text-decoration: none;' %>
    </button>
    <ul class="list">
        <% @post.comments.each do |comment| %>
            <li> <%= comment.author.name %>: <%= comment.text %> </li>
        <% end %>
    </ul>
</section>

app/views/comments/new.html.erb
<%= render 'layouts/header' %>
<section class="indent">
    <%= form_with model: Comment, url: user_post_comments_path(@post.author, @post) do |form| %>
        <div class="form">
            <%= form.label :Comment %>
            <%= form.text_area :text, size: "50x8" %>
        </div>
        <div>
            <%= form.submit "save"%>
            <button class="cancel-btn link">
                <%= link_to 'Cancel', user_post_path(@post.author, @post), style: 'color: black; text-decoration: none;' %>
            </button>
        </div>
    <% end %>
</section>

app/views/layouts/_header.html.erb
<header>
    <h1>HABASM AND MOHI</h1>
    <nav>
        <%= link_to "Home", root_path, class: "link" %>
        <% if user_signed_in? %>
            <%= link_to "New Post", new_user_post_path(current_user), class: "link" %>
            <%= link_to "Sign out", destroy_user_session_path, data: 
            {turbo_method: :delete, turbo_confirm: "Are you sure you want to log out?"}, class: "link" %>
        <% else %>
            <%= link_to "Sign up", new_user_registration_path, class: "link" %>
            <%= link_to "Log in", new_user_session_path, class: "link" %>
        <% end %>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "blog", media: "all" %>
    <%= javascript_importmap_tags %>
  </head>
  
  <body>
  <%= render 'layouts/header' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/likes/_like.html.erb
<div class="general-btn">
    <%= form_with model: Like, url: user_post_likes_path(@post.author, @post) do |form| %>
        <%= form.submit 'Like Post' %>
    <% end %>
</div>

app/views/posts/index.html.erb
<section class="indent">
    <div class="user-info">
        <img class="user-img" src=<%= @user.photo %>>
        <div class="bordered user">
            <span class="user-name"><%= @user.name %></span>
            <span class="user-offset">Number of posts: <%= @user.posts_counter %></span>
        </div>
    </div>
    <div class="page-description">
    <h3> List of previous Posts:</h3>
    <button class="page-btn">
        <%= link_to 'Create New Post', new_user_post_path(@user), style: 'color: black; text-decoration: none;' %>
    </button>
    </div>
    <% @posts.each do |post| %>
        <a class="link" href=<%= user_post_path(@user, post) %>>
            <section class="bordered post-info">
                Post <%= post.id %>: <%= post.title%><br><br>
                <%= truncate(post.text, length: 50, separator: ' ') %><br><br>
                <span class="offset-left">Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></span>
                <hr class="separator">
                <ul class="list">
                    <% post.recent_five.includes(:author).each do |comment| %>
                        <li> <%= comment.author.name %>: <%= comment.text %> </li>
                    <% end %>
                </ul>
            </section>
        </a>
    <% end %>
    <%= paginate @posts %>
</section>

app/views/posts/new.html.erb
<section class="indent">
    <fieldset>
        <legend>Create a new post:</legend>
        <%= form_with model: @post, url: user_posts_path, method: :post, local: true, scope: :post do |form| %>
            <div class="form">
                <%= form.label :title %>
                <%= form.text_field :title %>
            </div>
            <div class="form">
                <%= form.label :text %>
                <%= form.text_area :text, size: "60x12" %>
            </div>
            <div class="form">
                <%= form.submit "Post" %>
            </div>
        <% end %>
    </fieldset>
</section>

app/views/posts/show.html.erb
<button class="cancel-btn link indent">
        <%= link_to 'All posts', user_posts_path, style: 'color: black; text-decoration: none;' %>
</button>
<h3 class="indent"><%= @post.title %></h3>
<section class="bordered indent">
    <div class="post-stats">
        <span>Post <%= @post.id %> by <%= @post.author.name %></span>
        <span>Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></span>
    </div>
    <div class="post">
        <%= @post.text %>
        <br><br>
        <div class="post-actions">
            <button class="cancel-btn link">
                <%= link_to 'Add Comment', new_user_post_comment_path(@post.author, @post), style: 'color: black; text-decoration: none;' %>
            </button>
            <%= render 'likes/like' %>
        </div>
    </div>
    <hr class="separator">
    <ul class= "list">
        <% @post.comments.includes(:author).each do |comment| %>
            <li> <%= comment.author.name %>: <%= comment.text %> </li>
        <% end %>
    </ul>
</section>

app/views/users/_users.html.erb
<%= link_to user_path(user) do %>
    <li class="user">
      <div class="user-image">
        <%= image_tag user.photo, alt: "#{user.name}-avatar", class: 'w-36 h-36 object-cover object-center rounded-[50%]' %>
      </div>
      <div class="user-info">
        <h2 class="username"><%= user.name %></h2>
        <span class="count">Number of posts: <% if (user.posts_count == nil) %>
        <%= 0 %>
        <% else %>
        <%= user.posts_count %>
        <% end %>
        </span>
      </div>
    </li>
  <% end %>

app/views/users/index.html.erb
<section class="indent">
    <% if @users.empty? %>
        <h3>No users on record</h3>
    <% else %>
        <ul class="list">
            <% @users.each do |user| %>
                <li>
                    <a class="link" href=<%= user_path(user) %>>
                        <div class="user-info">
                            <img class="user-img" src=<%= user.photo %>>
                            <div class="bordered user">
                                <span class="user-name"><%= user.name %></span>
                                <span class="user-offset">Number of posts: <%= user.posts_counter %></span>
                            </div>
                        </div>
                    </a>
                </li>
            <% end %>
        </ul>
    <% end %>
</section>
    

app/views/users/show.html.erb
<section class="indent">
    <div class="user-info">
        <img class="user-img" src=<%= @user.photo %>>
        <div class="bordered user">
            <span class="user-name"><%= @user.name %></span>
            <span class="user-offset">Number of posts: <%= @user.posts_counter %></span>
        </div>
    </div>
    <div class="bordered">
        bio:<br><br>
        <%= @user.bio %><br><br>
    </div>
    <% @user.first_three.each do |post| %>
        <a class="link" href=<%= user_post_path(@user, post) %>>
            <div class="bordered post-info">
                Post <%= post.id %>:<%= post.title %><br><br>
                <%= truncate(post.text, length: 50, separator: ' ') %><br>
                <span class="offset-left">Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></span>
            </div>
        </a>
    <% end %>
    <button class="to-posts-btn">
        <%= link_to 'See all posts', user_posts_path(@user), style: 'color: black; text-decoration: none;' %>
    </button>
</section>